language: node_js

node_js:
  - stable

before_install:
# Install Neo4j locally:
- wget --no-check-certificate -O - https://debian.neo4j.org/neotechnology.gpg.key | sudo apt-key add -
- sudo echo 'deb http://debian.neo4j.org/repo stable/' > /etc/apt/sources.list.d/neo4j.list
- sudo apt-get update && apt-get install neo4j

- sudo service neo4j start
# HACK need to change the password initially; changing it and then reverting:
- sleep 10  # give Neo4J some time to start
- curl -v POST http://neo4j:neo4j@127.0.0.1:7474/user/neo4j/password -d"password=neo4j2"
- curl -v POST http://neo4j:neo4j2@127.0.0.1:7474/user/neo4j/password -d"password=neo4j"

install:
  - npm install

script:
  - npm test
  
# Send coverage data to Coveralls
after_script:
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js  

notifications:
  email:
    recipients:
      - andreas.leinen@imicros.de
    on_success: never # default: change
    on_failure: always # default: always