version: '3'
services:

  groups:
    build:
      context: .
    image: imicros-groups

    environment:
      SERVICES: groups

    external_links:
      - nats
      - neo4j_groups
      
    networks:
      - nats_default
      - neo4j_default
      
    restart: always

networks:
  nats_default:
    external: true
  neo4j_default:
    external: true
